repos:
  - repo: local
    hooks:
      - id: replace-gemini-api-key
        name: Replace Gemini API Key with Placeholder
        entry: |
          bash -c 'sed -i "" "s/GEMINI_API_KEY: '\''[^'\'']*'\''/GEMINI_API_KEY: '\''PLACEHOLDER'\''/g" config.js && git add config.js && echo "Updated config.js and staged the changes."'
        language: system
        files: config.js
        pass_filenames: false
